version : 3

tasks:
  build-user:
    cmds:
      - go build -o ./bin/user cmd/user/main.go
  run-user:
    cmds:
      - task build-user
      - ./bin/user
  build-music:
    cmds:
      - go build -o ./bin/music cmd/music/main.go
  run-user:
    cmds:
      - task build-music
      - ./bin/music