FROM golang:1.25.3-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/bin/main cmd/user/main.go

FROM alpine:3.18

RUN apk add --no-cache ca-certificates sqlite tzdata

RUN adduser -D -g '' appuser
RUN mkdir /data && chown appuser:appuser /data
VOLUME /data

WORKDIR /app

COPY --from=builder /app/bin/main ./main

COPY --chown=appuser:appuser database.sqlite /data/database.db

CMD ["./main"]